<a href="https://colab.research.google.com/github/khaleel-wilp/home/blob/main/np_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
x = np.arange(10)
print(x)
print(x[:5])
print(x[5:])
print(x[4:8])
print(x[::2])
print(x[2::3])
print(x[::-1])
print(x[7::-2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6 7]
[0 2 4 6 8]
[2 5 8]
[9 8 7 6 5 4 3 2 1 0]
[7 5 3 1]


In [27]:
y = np.arange(15).reshape(3,5)
print(y)
print(y[0])
print(y[:,0])
print(y[:2,:3])
print(y[:2,::2])
print(y[::-1])
print(y[:,::-1])
print(y[::-1,::-1])
print(y[::2,::2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2 3 4]
[ 0  5 10]
[[0 1 2]
 [5 6 7]]
[[0 2 4]
 [5 7 9]]
[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]]
[[14 13 12 11 10]
 [ 9  8  7  6  5]
 [ 4  3  2  1  0]]
[[ 0  2  4]
 [10 12 14]]


In [36]:
z = np.arange(60).reshape(3,4,5)
print(z)
print(z[0])
print(z[0][1])
print(z[0,1])
print(z[1][1][4])
print(z[1,1,4])
print(z[1:,0])
print(z[1:,0:2,1:4])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[5 6 7 8 9]
[5 6 7 8 9]
29
29
[[20 21 22 23 24]
 [40 41 42 43 44]]
[[[21 22 23]
  [26 27 28]]

 [[41 42 43]
  [46 47 48]]]
